"""empty message

Revision ID: 341dab348bca
Revises: 1381fef00bbd
Create Date: 2022-10-21 12:24:04.854033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341dab348bca'
down_revision = '1381fef00bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
