"""empty message

Revision ID: 41316da2fc1b
Revises: 341dab348bca
Create Date: 2022-10-28 11:42:25.489217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41316da2fc1b'
down_revision = '341dab348bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint("email", 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
